### ISSUE TITLE
Installer/Artifacts

### ISSUE THREAD

**Issue by jameswelle** [heaths/psmsi#1]
Hi Heath,

I noticed your AppVeyor build doesn't produce any artifacts. What is the recommended way to get the latest install of this project?

Thanks!
James

**Comment by heaths** [comment]
Sorry, yes. I need to get that set up. There haven't been any functional changes just yet. If you have Windows 10 or the WMF 5.0 Preview installed, you can use OneGet like so:

``` powershell
install-package msi -provider psmodule
```

The latest drops are also on the original site at http://psmsi.codeplex.com under Releases.

**Comment by heaths** [comment]
You can get them from the AppVeyor build artifacts page. I'll be setting up publication automation soon.
