### ISSUE TITLE
How do I install psmsi?

### ISSUE THREAD

**Issue by haggis999** [heaths/psmsi#10]
I used to have a small system SSD and therefore chose to install Visual Studio Professional 2015 on my G: drive. After upgrading to a much bigger SSD, I now wish to reinstall VS 2015 on my C: drive, but the installer refuses to allow me to move away from the original G: location, even after uninstalling every app with Visual Studio in its name.

I then found your blog post at https://blogs.msdn.microsoft.com/heaths/2015/07/14/how-to-install-visual-studio-to-another-directory-when-a-pre-release-is-installed/.

I have downloaded psmsi from GitHub (using the Clone or Download button) but have no idea how to install it on my Windows 10 computer.  Some guidance would be much appreciated. Please note that I know absolutely nothing about GitHub.

**Comment by heaths** [comment]
On Windows 10, open powershell and run the following (much easier to install and update; I'll be removing the MSI eventually anyway):

```powershell
install-module msi -scope currentuser
```

**Comment by haggis999** [comment]
Hi Heath,
Many thanks for the info. I've never dabbled with Powershell before but I managed to open a Powershell prompt and tried running 'install-module msi -scope currentuser'. This prompted me to install something called Nuget. However, when I tried running ' install-module msi -scope currentuser' again it did not generate any message. I was simply returned to the Powershell prompt.

 

Where do I go from here? 

 

Best regards,
David

**Comment by heaths** [comment]
Nuget is a popular package manager for building solutions - no doubt you'll want to use this with Visual Studio is writing code. The PowerShellGet module (installed with WMF 5 / Windows 10) requires it once to pull from http://powershellgallery.com. Once installed, any module that installs without error should just work. Try running `get-msiproductinfo` and that will verify my module is installed.

I recommend reading up on using powershell from Microsoft TechNet. There's lots of good tutorials and large user communities to help as well. Back and forth in a bug reporting system probably isn't the best approach for learning powershell. ;)

**Comment by haggis999** [comment]
I've always managed to build .NET websites without any obvious need for either Nuget or Powershell, but I'll check them out in more detail when I get the time. My current objective is simply to reinstall VS 2015 on a different drive from the original installation, a process that Microsoft seems to have made much more difficult than I expected.

I was prompted to get Nuget from psgallery. No errors or warnings appeared, so I presume it installed correctly.  However, when I ran get-msiproductinfo I was told that "The 'get-msiproductinfo' command was found in the module 'MSI', but the module could not be loaded. For more information, run 'Import-Module MSI'".

Further investigation suggests that I need to change the Powershell execution policy from 'Restricted' to 'AllSigned'. I'm currently working my way through that process...

**Comment by haggis999** [comment]
I ran Powershell in Administrator mode, which let me change the execution policy from 'Restricted' to 'AllSigned', but nothing relevant is working as the code from psgallery appears to be unsigned. Rather reluctantly, I tried to set an execution policy of Unrestricted, but it was overridden by the system.

No doubt there is a way for me to force an execution policy of Unrestricted, but is this really the recommended approach?

**Comment by heaths** [comment]
You'll find many modules unsigned. I recommend 'RemoteSigned' so at least content on UNC paths needs to be signed. If you have some admin policy overriding that, I really can't help you.

For problems with Visual Studio, I recommend you contact Customer Support Services at http://support.microsoft.com. I'm not sure what you plan to do with the module anyway, as it won't necessarily fix the problem that's probably caused by one or more components still installed to your previous drive. This has to be fixed outside the scope of this project.

**Comment by haggis999** [comment]
I'm only trying to run your module because your blog recommended it as the solution for identifying which installed components are preventing relocation of VS 2015 (ref the link quoted in my OP).

I'm just running vanilla Windows 10 Professional and know nothing about admin policies, but it looks like I will have to do some Googling on that topic, as my attempt to set RemoteSigned was also overridden.

**Comment by haggis999** [comment]
Hi Heath,
I eventually succeeded in changing the execution policy to 'RemoteSigned' with the help of the following link.
- https://blogs.msdn.microsoft.com/pasen/2011/12/07/set-executionpolicy-windows-powershell-updated-your-execution-policy-successfully-but-the-setting-is-overridden-by-a-policy-defined-at-a-more-specific-scope/

This then let me run the remaining two steps for identifying and uninstalling the component that was preventing the relocation of VS 2015, as per your blog. **My original problem is thus resolved**. I am very grateful to you for taking the time to generate what was to me a highly obscure solution that I would never have been able to create for myself, and for assisting me in making it work    ;-)

That said, I am still puzzled as to why Microsoft makes the relocation of Visual Studio so complicated! It would be far more user friendly if the VS installation procedure was able to identify which components were preventing relocation.
