### ISSUE TITLE
Unable to find package MSI: How to install?

### ISSUE THREAD

**Issue by lboening** [heaths/psmsi#19]
I was unable to find the package MSI. I run Windows 7, Powershell 5.

                                                              
PSVersion                      5.0.10586.117                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                
BuildVersion                   10.0.10586.117                                                         
CLRVersion                     4.0.30319.42000                                                        
WSManStackVersion              3.0                                                                    
PSRemotingProtocolVersion      2.3                                                                    
SerializationVersion           1.1.0.1          

I am on Windows 7 and must struggle with Powershell parts that haven't been written to work on Windows 7, only Windows 10 etc.

I suppose I can install another way, just downloading and running the MSI.         

Well, that worked. But, where do I find the PSM1 or PS1 files? I did not see them pop into any module directory.

**Comment by heaths** [comment]
1. The MSI is available on the [releases](https://github.com/heaths/psmsi/releases) page.
2. You really should not use the MSI; I'm going to get rid of it eventually. Instead, in PowerShell 5 you should get the PackageManagement module, which lets you simply do: `install-package MSI`.
3. You'd need to restart the PowerShell environment when using the MSI. The MSI updates the `PSMODULEPATH` environment because of design issues with how PowerShell dictated module locations that don't jive with Windows' own guidelines on install locations (i.e. not in Documents folder).

**Comment by lboening** [comment]
I was able to install the module using the command on Windows 10. There is probably a better way to install it as a PSM1 module. You have that, I assume, but I could not find it.

**Comment by heaths** [comment]
With the PackageManagement module, you should be able to do that just fine in Windows 7. If not, you can use the MSI but you need to restart PowerShell afterward. Console-based applications like powershell.exe do not automatically get refreshed when the machine environment is updated.

**Comment by lboening** [comment]
I found the module under Chocolatey. It is called PSMSI. Is your front matter, calling it MSI, correct?

**Comment by heaths** [comment]
Do not use the Chocolatey package. I haven't updated that in years (and won't). Did you look at the Release link I sent you originally? It's on the Releases tab on this very site where you can find the MSI. The chocolatey package was not an MSI, nor is it necessary when using `install-package MSI` (or `install-module MSI`, which is recommended and the MSI will go away).

**Comment by lboening** [comment]
Aha, the module might be in two different galleries. I found the "MSI" one at PSGallery.
[out.txt](https://github.com/heaths/psmsi/files/625365/out.txt)

My default providers on my other Windows machine, running Visual Studio, points to Chocolatey and Nuget, but not PsGallery.

Are you able to delete the version on Chocolatey?

**Comment by heaths** [comment]
No need. You control what providers are used, or use install-module which uses the psgallery by default. The Choco version remains for people that used those versions and want to restore them. It predates OneGet and new versions will not go there.

**Comment by lboening** [comment]
That is fine. It was confusing for me. It did help me figure out that across three different machines, Windows 7 and Windows 10, I have Powershell configuration problems on two.
