### ISSUE TITLE
The process cannot access the file 'C:\Program Files\WindowsPowerShell\Modules\MSI\3.2.26.21626\Microsoft.Deployment.Compression.dll' because it is being used by another process.

### ISSUE THREAD

**Issue by SergeDubovsky** [heaths/psmsi#25]
Install-MSIProduct $output -Verbose worked once, on a second run, I got the message "is being used by another process". Is there any way to troubleshoot this?

Thank you.

**Comment by heaths** [comment]
It's likely a problem with anti-virus / malware detection. Unfortunately, it seems more frequent that files are being opened too long or with the wrong oplock. We run into this all the time with our setup chainers and the work around is to retry the install. If you want to troubleshoot what has it open, Process Monitor from https://sysinternals.com (will redirect to Microsoft) is great or you can use the Kernel Trace Logger with the "(process,img)" keywords but that is harder to read/process. I recommend procmon.
