### ISSUE TITLE
set target/destination not effect with install-msiproduct

### ISSUE THREAD

**Issue by zpf1989** [heaths/psmsi#33]
Hello,thanks for your great job.
I want to install redis using a Redis-x64-3.2.100.msi on my WindowsServer 2012R2 with WMF5.1.
I execute the cmd below in powershell:
```
$src='C:\ps\src\Redis-x64-3.2.100.msi'
install-msiproduct $src -destination C:\install\redis -log C:\ps\src\install.log
```
When done,the destination of redis is "C:\Program Files\Redis",not the "C:\install\redis" as my set.
Here is my install log:
[install_20180730023825_000_Redis-x64-3.2.100.log](https://github.com/heaths/psmsi/files/2239973/install_20180730023825_000_Redis-x64-3.2.100.log)

Did I miss something?
Please give me a help,thanks a lot!

**Comment by heaths** [comment]
It depends on how the MSI authors its `Directory` table. `-Destination` just sets `TARGETDIR`. Many MSIs do not use the `TARGETDIR` as the root. Visual Studio hasn't in many releases, for example.

**Comment by zpf1989** [comment]
Yes,it works.
Thank you very much!
