### ISSUE TITLE
Unable to load module in PowerShell v2

### ISSUE THREAD

**Issue by jngibert** [heaths/psmsi#34]
On computers that only have PowerShell v2 installed, or when running later versions of PowerShell using the -version 2.0 command line switch, importing this MSI module returns the error: **Could not load file or assembly <path>\Microsoft.Tools.WindowsInstaller.PowerShell.dll or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.**

Because of the dependency on the installation of newer NET Frameworks, many businesses (including ours) still have computers where we cannot install the latest version of PowerShell. For the next few years (until Win7 and Server 2008 R2 go off of support - and maybe a little beyond that) we will still need to support PowerShell v2.

Will you please either update the documentation to properly reflect the minimum version of PowerShell that is supported by the module, or provide DLLs that will work correctly with PowerShell version 2.0.

Is it possible to provide basic functionality that was in version 2.2.x via DLLs compiled specifically for PowerShell v2, while the newer DLLs would be dynamically used with newer versions of PowerShell?

**Comment by heaths** [comment]
Based on https://archive.codeplex.com/?p=psmsi, issue titled "Error importing module in PS 2.0", apparently this was supposed to be fixed but clearly was incomplete. I suppose on test systems with PowerShell 2.0 with newer Frameworks installed it worked, but passing `-version 2.0` might more strictly limit that.

I should be able to make this change to support it from an initial investigation.

**Comment by jngibert** [comment]
Thanks, Heath.  Let me know if you need help gathering info or testing.  I have access to a large collection of systems in our corporate lab.

**Comment by heaths** [comment]
I was able to test it, but thanks. :) Unfortunately, I'm having build pipeline issues right now and have to sort that out, but if you want to clone the source and build from this PR branch its ready. I might initially do a pre-release while I add some container-based tests like I have for some other projects so that I can properly test in v2 through v5 environments before merging into master / releasing.

**Comment by jngibert** [comment]
I was able to compile from the source. Testing so far using Powershell v2 has been successful.  Thank you very much!  Hope you get the pipeline sorted soon.

**Comment by heaths** [comment]
Glad a private is working for now. I'm converting to Azure Pipelines for build/release. I'll have more time to tackle that over Thanksgiving vacation so I should have a release soon thereafter.

**Comment by heaths** [comment]
I pushed a pre-release version you can install with `install-module -allowpre msi -force`, or update using `update-module` with the same parameters. I'll give this a little time and make sure there's no regressions, than can promote to a full release.
