### ISSUE TITLE
command not recognized in powershell after install psmsi.msi on windows 7

### ISSUE THREAD

**Issue by greylander** [heaths/psmsi#6]
3.0.3+1 (Build 46) is the one I tried.

No indication in install instructions of needing to set a path or other configuration of powershell.  I have attempted both all/single with and without admin elevation.

Install, open a powershell, get "the term .... not recognized" for commands such as get-msiproductinfo.

Sorry if this is not the best route to ask this question. Seems it was this or a comment on your blog.  Am I missing something that powershell experts "just know" to do?
Thanks!

**Comment by heaths** [comment]
How did you install it? You need to either use the MSI installer, or if using WMF you can use the `install-package` or `install-module` cmdlets. Either hook up the path. If you use the ZIP, you need to either extract it to your Modules directory or set the PATH yourself. ZIPs can't do that.

**Comment by heaths** [comment]
Sorry, I see you did use the MSI installer from the title. Note that when any installer (batch, Windows Installer, etc.) update environment variables like `PATH` command shells (at least built-in ones like cmd.exe and things like powershell.exe that run within cmd.exe) do not automatically pick up those changes. You need to restart the environment. That should work and, so far as I know, has for anyone I know using it.

If not, please reopen this bug and share out what your PSMODULEPATH and PATH environment variables expand to, ex:

```powershell
$env:PATH
$env:PSMODULEPATH
```

**Comment by alex-chan** [comment]
It does not work. My env:

`PS C:\Users\Administrator> $env:PATH
%SystemRoot%\system32\WindowsPowerShell\v1.0\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System
32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\Python27;D:\Python27\Scripts;C:\Us
ers\Administrator\AppData\Local\Programs\Windows Installer PowerShell Module`

`PS C:\Users\Administrator> $env:PSMODULEPATH
%PSMODULEPATH%;C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Users\Administrator\AppData\Local\Programs\Window
s Installer PowerShell Module\`

**Comment by heaths** [comment]
@alex-chan What specifically does not work? Your environment looks right.

It's better you stop using the MSI anyway. Just use `install-module msi` (or `install-package msi`, but it has a wider set of sources it queries) and everything works fine.

**Comment by zzpbuaa** [comment]
Hi, we encounter a similar case, and we resolve it by "import" module in script. Because on some version of Powershell, it does not import all available module automatically. On some win7 system, it has this kind of powershell.

I don't know if my issue is related, just for your information.

**Comment by heaths** [comment]
Not an issue with this module, but a limitation of older versions of PowerShell that some automatically import.
