### ISSUE TITLE
Can not download installer

### ISSUE THREAD

**Issue by UriF** [heaths/psmsi#9]
I downloaded a msi from http://psmsi.codeplex.com/.  
From the site  https://github.com/heaths/psmsi I can download a project only or install github.   
I tried to open a project with VS 2015 community but I got message that this version not supported 

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - Module, "D:\Downloads\WindowsUpdateMiniTools\psmsi-master\psmsi-master\src\Setup\Module.wixproj"

No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - Setup, "Setup"
	 - PowerShell, "D:\Downloads\WindowsUpdateMiniTools\psmsi-master\psmsi-master\src\PowerShell\PowerShell.csproj"
	 - PowerShell.Test, "D:\Downloads\WindowsUpdateMiniTools\psmsi-master\psmsi-master\test\PowerShell.Test\PowerShell.Test.csproj"
	 - .nuget, ".nuget"
	 - Psmsi, "D:\Downloads\WindowsUpdateMiniTools\psmsi-master\psmsi-master\Psmsi.sln"Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - Module, "D:\Downloads\WindowsUpdateMiniTools\psmsi-master\psmsi-master\src\Setup\Module.wixproj"

No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - Setup, "Setup"
	 - PowerShell, "D:\Downloads\WindowsUpdateMiniTools\psmsi-master\psmsi-master\src\PowerShell\PowerShell.csproj"
	 - PowerShell.Test, "D:\Downloads\WindowsUpdateMiniTools\psmsi-master\psmsi-master\test\PowerShell.Test\PowerShell.Test.csproj"
	 - .nuget, ".nuget"
	 - Psmsi, "D:\Downloads\WindowsUpdateMiniTools\psmsi-master\psmsi-master\Psmsi.sln"

**Comment by heaths** [comment]
What exactly is this bug about? If you're trying to download the MSI, newer versions are available from https://github.com/heaths/psmsi/releases. But you're also trying to open the solution from source? You need to install the latest 3.x release of wix: http://wixtoolset.org.

**Comment by UriF** [comment]
Sorry, could not find this link
